=== Chu5Cang/BaiTapNhom22_XML_DeTai23/htqlbaigiuxe.dtd
<!ELEMENT hethongbaigiuxe (khachhangs, xes, loaixes, banggias, thexes, luotgiuxes, hoadons, nhanviens, lichphancongs, calams)>

<!ELEMENT khachhangs (khachhang+)>
<!ELEMENT khachhang (makh, hoten, gioitinh, sdt, diachi)>
<!ELEMENT makh (#PCDATA)>
<!ELEMENT hoten (#PCDATA)>
<!ELEMENT gioitinh (#PCDATA)>
<!ELEMENT sdt (#PCDATA)>
<!ELEMENT diachi (#PCDATA)>

<!ELEMENT xes (xe+)>
<!ELEMENT xe (bienso, malx, makh)>
<!ELEMENT bienso (#PCDATA)>
<!ELEMENT malx (#PCDATA)>

<!ELEMENT loaixes (loaixe+)>
<!ELEMENT loaixe (malx, tenloaixe)>
<!ELEMENT tenloaixe (#PCDATA)>

<!ELEMENT banggias (banggia+)>
<!ELEMENT banggia (mabg, malx, giatheogio)>
<!ELEMENT mabg (#PCDATA)>
<!ELEMENT giatheogio (#PCDATA)>

<!ELEMENT thexes (thexe+)>
<!ELEMENT thexe (mathe, trangthai)>
<!ELEMENT mathe (#PCDATA)>
<!ELEMENT trangthai (#PCDATA)>

<!ELEMENT luotgiuxes (luotgiuxe+)>
<!ELEMENT luotgiuxe (maluot, bienso, mathe, thoigianvao, thoigianra, mapc)>
<!ELEMENT maluot (#PCDATA)>
<!ELEMENT thoigianvao (#PCDATA)>
<!ELEMENT thoigianra (#PCDATA)>
<!ELEMENT mapc (#PCDATA)>

<!ELEMENT hoadons (hoadon+)>
<!ELEMENT hoadon (mahd, maluot, ngaylap, tongtien)>
<!ELEMENT mahd (#PCDATA)>
<!ELEMENT ngaylap (#PCDATA)>
<!ELEMENT tongtien (#PCDATA)>

<!ELEMENT nhanviens (nhanvien+)>
<!ELEMENT nhanvien (manv, hoten, gioitinh, sdt, diachi, chucvu)>
<!ELEMENT manv (#PCDATA)>
<!ELEMENT chucvu (#PCDATA)>

<!ELEMENT lichphancongs (lichphancong+)>
<!ELEMENT lichphancong (mapc, manv, macl, ngayphancong)>
<!ELEMENT mapc (#PCDATA)>
<!ELEMENT ngayphancong (#PCDATA)>

<!ELEMENT calams (calam+)>
<!ELEMENT calam (macl, tencalam, giobatdau, gioketthuc)>
<!ELEMENT macl (#PCDATA)>
<!ELEMENT tencalam (#PCDATA)>
<!ELEMENT giobatdau (#PCDATA)>
<!ELEMENT gioketthuc (#PCDATA)>

=== Chu5Cang/BaiTapNhom22_XML_DeTai23/htqlbaigiuxe_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hethongbaigiuxe SYSTEM "htqlbaigiuxe.dtd">

<hethongbaigiuxe> 
    <!-- Khách hàng -->
    <khachhang makh="KH24000001">
        <hoten>Nguyễn Huy Khang</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0912345678</sdt>
        <diachi>123 Cái Khế, Quận Ninh Kiều, TP.Cần Thơ</diachi>
    </khachhang>
    <khachhang makh="KH24000002">
        <hoten>Trần Thị Bích</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0987654321</sdt>
        <diachi>45 Nguyễn Trãi, Quận 5, TP.HCM</diachi>
    </khachhang>
    <khachhang makh="KH24000003">
        <hoten>Lê Văn Cường</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0901234567</sdt>
        <diachi>12 Trần Hưng Đạo, Quận Ninh Kiều, TP.Cần Thơ</diachi>
    </khachhang>
    <khachhang makh="KH24000004">
        <hoten>Phạm Hường Châu</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0978123456</sdt>
        <diachi>78 Hai Bà Trưng, Hà Nội</diachi>
    </khachhang>
    <khachhang makh="KH24000005">
        <hoten>Võ Hoàng Khoa</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0934567890</sdt>
        <diachi>56 Cách Mạng Tháng 8, Quận 3, TP.HCM</diachi>
    </khachhang>
    <khachhang makh="KH24000006">
        <hoten>Nguyễn Thị Lan</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0911122233</sdt>
        <diachi>34 Lý Thường Kiệt, Huế</diachi>
    </khachhang>
    <khachhang makh="KH24000007">
        <hoten>Đặng Quang Huy</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0944455566</sdt>
        <diachi>89 Võ Thị Sáu, Vũng Tàu</diachi>
    </khachhang>
    <khachhang makh="KH24000008">
        <hoten>Trần Kim Ngân</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0923344556</sdt>
        <diachi>21 Nguyễn Văn Cừ, Cần Thơ</diachi>
    </khachhang>
    <khachhang makh="KH24000009">
        <hoten>Hoàng Tuấn Kiệt</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0967788990</sdt>
        <diachi>67 Phan Đình Phùng, Đà Lạt</diachi>
    </khachhang>
    <khachhang makh="KH24000010">
        <hoten>Nguyễn Bảo Hân</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0933111222</sdt>
        <diachi>145 Điện Biên Phủ, Bình Thạnh, TP.HCM</diachi>
    </khachhang>
    
    <!-- Nhân viên -->
    <nhanvien manv="NV24000001">
        <hoten>Nguyễn Văn Minh</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0909123456</sdt>
        <diachi>12 Lê Lợi, TP.Cần Thơ</diachi>
        <chucvu>Phát Thẻ</chucvu>
    </nhanvien>
    <nhanvien manv="NV24000002">
        <hoten>Trần Thị Hạnh</hoten>
        <gioitinh>Nữ</gioitinh>
        <sdt>0934455667</sdt>
        <diachi>45 Nguyễn Văn Cừ, Cần Thơ</diachi>
        <chucvu>Sắp Xếp Xe</chucvu>
    </nhanvien>
    <nhanvien manv="NV24000003">
        <hoten>Lê Văn Hùng</hoten>
        <gioitinh>Nam</gioitinh>
        <sdt>0912345678</sdt>
        <diachi>78 Trần Phú, Đà Nẵng</diachi>
        <chucvu>Sắp Xếp Xe</chucvu>
    </nhanvien>
    
    <!-- Bảng giá -->
    <banggia mabg="BG0001">
        <giatheogio>5000</giatheogio>
    </banggia>
    <banggia mabg="BG0002">
        <giatheogio>10000</giatheogio>
    </banggia>
    
    <!-- Ca làm -->
    <calam macl="CA01">
        <tencalam>Sáng</tencalam>
        <giobatdau>06:00:00</giobatdau>
        <gioketthuc>14:00:00</gioketthuc>
    </calam>
    <calam macl="CA02">
        <tencalam>Chiều</tencalam>
        <giobatdau>14:00:00</giobatdau>
        <gioketthuc>22:00:00</gioketthuc>
    </calam>
    <calam macl="CA03">
        <tencalam>Tối</tencalam>
        <giobatdau>22:00:00</giobatdau>
        <gioketthuc>06:00:00</gioketthuc>
    </calam>
    
    <!-- Thẻ xe -->
    <thexe mathe="TX1">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX2">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX3">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX4">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX5">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX6">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX7">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX8">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX9">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX10">
        <trangthai giatri="true"></trangthai>
    </thexe>
    <thexe mathe="TX11">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX12">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX13">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX14">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX15">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX16">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX17">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX18">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX19">
        <trangthai giatri="false"></trangthai>
    </thexe>
    <thexe mathe="TX20">
        <trangthai giatri="false"></trangthai>
    </thexe>
    
    <!-- Loại xe -->
    <loaixe malx="LX0001" mabgRef="BG0001">
        <tenloaixe>Xe máy</tenloaixe>
    </loaixe>
    <loaixe malx="LX0002" mabgRef="BG0002">
        <tenloaixe>Xe Ô tô</tenloaixe>
    </loaixe>
    
    <!-- Xe -->
    <xe bienso="BS_79A-123.45" makhRef="KH24000001" malxRef="LX0001"/>
    <xe bienso="BS_59B-678.90" makhRef="KH24000002" malxRef="LX0002"/>
    <xe bienso="BS_43C-112.23" makhRef="KH24000003" malxRef="LX0001"/>
    <xe bienso="BS_81D-445.56" makhRef="KH24000004" malxRef="LX0002"/>
    <xe bienso="BS_72E-778.89" makhRef="KH24000005" malxRef="LX0001"/>
    <xe bienso="BS_50F-990.01" makhRef="KH24000006" malxRef="LX0002"/>
    <xe bienso="BS_88G-223.34" makhRef="KH24000007" malxRef="LX0001"/>
    <xe bienso="BS_66H-556.67" makhRef="KH24000008" malxRef="LX0002"/>
    <xe bienso="BS_39K-889.90" makhRef="KH24000009" malxRef="LX0001"/>
    <xe bienso="BS_77L-101.12" makhRef="KH24000010" malxRef="LX0002"/>
    
    <!-- Lịch phân công -->
    <lichphancong mapc="PC1" manvRef ="NV24000001" maclRef="CA01">
        <ngayphancong>2024-10-01</ngayphancong>
    </lichphancong>   
    <lichphancong mapc="PC2" manvRef ="NV24000002" maclRef="CA02">
        <ngayphancong>2024-10-01</ngayphancong>
    </lichphancong>
    <lichphancong mapc="PC3" manvRef ="NV24000003" maclRef="CA03">
        <ngayphancong>2024-10-01</ngayphancong>
    </lichphancong>
    
    
    <!-- Lượt giữ xe -->
    <luotgiuxe maluot="L1" biensoRef="BS_79A-123.45" matheRef="TX1" mapcRef="PC1">
        <thoigianvao>2024-10-01T09:30:00</thoigianvao>
        <thoigianra>2024-10-01T11:30:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L2" biensoRef="BS_59B-678.90" matheRef="TX2" mapcRef="PC1">
        <thoigianvao>2024-10-01T10:00:00</thoigianvao>
        <thoigianra>2024-10-01T12:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L3" biensoRef="BS_43C-112.23" matheRef="TX3" mapcRef="PC2">
        <thoigianvao>2024-10-01T11:00:00</thoigianvao>
        <thoigianra>2024-10-01T13:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L4" biensoRef="BS_81D-445.56" matheRef="TX4" mapcRef="PC2">
        <thoigianvao>2024-10-01T12:30:00</thoigianvao>
        <thoigianra>2024-10-01T14:30:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L5" biensoRef="BS_72E-778.89" matheRef="TX5" mapcRef="PC3">
        <thoigianvao>2024-10-01T13:00:00</thoigianvao>
        <thoigianra>2024-10-01T15:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L6" biensoRef="BS_50F-990.01" matheRef="TX6" mapcRef="PC3">
        <thoigianvao>2024-10-01T14:00:00</thoigianvao>
        <thoigianra>2024-10-01T16:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L7" biensoRef="BS_88G-223.34" matheRef="TX7" mapcRef="PC1">
        <thoigianvao>2024-10-01T15:30:00</thoigianvao>
        <thoigianra>2024-10-01T17:30:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L8" biensoRef="BS_66H-556.67" matheRef="TX8" mapcRef="PC1">
        <thoigianvao>2024-10-01T16:00:00</thoigianvao>
        <thoigianra>2024-10-01T18:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L9" biensoRef="BS_39K-889.90" matheRef="TX9" mapcRef="PC2">
        <thoigianvao>2024-10-01T17:00:00</thoigianvao>
        <thoigianra>2024-10-01T19:00:00</thoigianra>
    </luotgiuxe>
    <luotgiuxe maluot="L10" biensoRef="BS_77L-101.12" matheRef="TX10" mapcRef="PC2">
        <thoigianvao>2024-10-01T18:30:00</thoigianvao>
        <thoigianra>2024-10-01T20:30:00</thoigianra>
    </luotgiuxe>
    
    <!-- Hóa đơn -->
    <hoadon mahd="HD24000001" maluotRef="L1">
        <ngaylap>2024-10-01T11:35:00</ngaylap>
        <tongtien>10000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000002" maluotRef="L2">
        <ngaylap>2024-10-01T12:05:00</ngaylap>
        <tongtien>20000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000003" maluotRef="L3">
        <ngaylap>2024-10-01T13:05:00</ngaylap>
        <tongtien>15000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000004" maluotRef="L4">
        <ngaylap>2024-10-01T14:35:00</ngaylap>
        <tongtien>25000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000005" maluotRef="L5">
        <ngaylap>2024-10-01T15:05:00</ngaylap>
        <tongtien>10000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000006" maluotRef="L6">
        <ngaylap>2024-10-01T16:05:00</ngaylap>
        <tongtien>20000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000007" maluotRef="L7">
        <ngaylap>2024-10-01T17:35:00</ngaylap>
        <tongtien>15000</tongtien>
    </hoadon>
    <hoadon mahd="HD24000008" maluotRef="L8">
        <ngaylap>2024-10-01T18:05:00</ngaylap>
        <tongtien>25000</tongtien>
    </hoadon>
